---
- hosts: all
  remote_user: root
  vars:
    compose_directory: /data/bananaland.minetest.ch
  tasks:
    - name: Checkout git master
      ansible.builtin.git:
        repo: https://github.com/banananaland/bananaland.minetest.ch
        dest: "{{ compose_directory }}"
        single_branch: yes
        force: yes
        version: master

    - name: Template minetest config
      template:
        src: "minetest.conf"
        dest: "{{compose_directory}}/data/minetest/minetest.conf"

    - name: Template matterbridge config
      template:
        src: "matterbridge.toml"
        dest: "{{compose_directory}}/matterbridge.toml"

    - name: Template docker-compose
      template:
        src: "docker-compose.yml"
        dest: "{{compose_directory}}/docker-compose.yml"

    - name: Create and start services
      community.docker.docker_compose_v2:
        project_src: "{{ compose_directory }}"
        pull: "always"
        build: "always"
        remove_orphans: yes

    - name: Reload nginx config
      shell:
        cmd: "docker-compose exec -T nginx nginx -s reload"
        chdir: "{{ compose_directory }}"
