---
- hosts: all
  remote_user: root
  vars:
    compose_directory: /data/bananaland.minetest.ch
  tasks:
    - name: Checkout git master
      ansible.builtin.git:
        repo: https://github.com/banananaland/bananaland.minetest.ch
        dest: "{{ compose_directory }}"
        single_branch: yes
        version: master

    - name: Template minetest config
      template:
        src: "minetest.conf"
        dest: "{{compose_directory}}/data/minetest/minetest.conf"

    - name: Create and start services
      community.general.docker_compose:
        project_src: "{{ compose_directory }}"
        pull: yes
        build: yes
        remove_orphans: yes
